on:
  push:
    branches:
      - "*" # Runs on all branches
  pull_request:
    branches:
      - "*" # Runs on all branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required for SonarQube analysis

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Create .env file
        run: |
          echo "DB_CONN_STRING=${{ secrets.DB_CONN_STRING }}" >> chathaven/.env
          echo "DB_NAME=chatHavenDB" >> chathaven/.env
          echo "PORT=3000" >> chathaven/.env
          echo "FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> chathaven/.env
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> chathaven/.env

      - name: Install backend dependencies
        working-directory: ./chathaven/backend
        run: npm ci

      - name: Install frontend dependencies
        working-directory: ./chathaven/frontend
        run: npm ci

      - name: Run Jest Unit Tests
        working-directory: ./chathaven/backend
        run: npm test

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          projectBaseDir: ./chathaven/backend
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
